#include <stdio.h>
#include <stdlib.h>
#include "DoubleLinkedList.h"

Node_t *List = NULL;
List_Status Status = ERROR ;
uint32_t Length = ZERO_INIT ;
uint64_t Data = ZERO_INIT ;

uint64_t Data1 = 1 ;
uint64_t Data2 = 2 ;
uint64_t Data3 = 3;
uint64_t Data4 = 4 ;
uint64_t Data5 = 5 ;
uint64_t Data6 = 6 ;
uint64_t Data7 = 7 ;
uint64_t Data8 = 8 ;
uint64_t Data9 = 9 ;
uint64_t Data10 = 10 ;

uint64_t Data11 = 1763 ;
uint64_t Data12 = 1347 ;
uint64_t Data13 = 124782 ;

int main()
{
    Status = Insert_Beggining(&List ,Data1) ;printf("Data to inserte in the Start of List = %d \t",Data1) ;printf("Status of Insertion Data = %d \n",Status) ;
    Status = Insert_Beggining(&List ,Data2) ;printf("Data to inserte in the Start of List = %d \t",Data2) ;printf("Status of Insertion Data = %d \n",Status) ;
    Status = Insert_Beggining(&List ,Data3) ;printf("Data to inserte in the Start of List = %d \t",Data3) ;printf("Status of Insertion Data = %d \n",Status) ;
    Status = Insert_Beggining(&List ,Data4) ;printf("Data to inserte in the Start of List = %d \t",Data4) ;printf("Status of Insertion Data = %d \n",Status) ;
    Status = Insert_Beggining(&List ,Data5) ;printf("Data to inserte in the Start of List = %d \t",Data5) ;printf("Status of Insertion Data = %d \n",Status) ;
    Status = Insert_Beggining(&List ,Data6) ;printf("Data to inserte in the Start of List = %d \t",Data6) ;printf("Status of Insertion Data = %d \n",Status) ;
    printf("------------------------------------------------\n") ;
    Status = Display_Forward_Data(List) ;printf("Status of Display Data Forward = %d \n",Status) ;
    printf("------------------------------------------------\n") ;
    Status = Display_Back_Data(List) ;printf("Status of Display Data Back = %d \n",Status) ;
    printf("------------------------------------------------\n") ;
    Status = Display_Forward_Addressies(List) ;printf("Status of Display Data Forward = %d \n",Status) ;
    printf("------------------------------------------------\n") ;
    Status = Display_Back_Addressies(List) ;printf("Status of Display Data Back = %d \n",Status) ;
    printf("------------------------------------------------\n") ;
    Length = GetLength(List) ;printf("Number of the Element in the List = %d \n",Length) ;
    printf("------------------------------------------------\n") ;
    Status = Insert_End(&List ,Data7) ;printf("Data to inserte in the End List = %d \t",Data7) ;printf("Status of Insertion Data = %d \n",Status) ;
    Status = Insert_End(&List ,Data8) ;printf("Data to inserte in the End List = %d \t",Data8) ;printf("Status of Insertion Data = %d \n",Status) ;
    Status = Insert_End(&List ,Data9) ;printf("Data to inserte in the End List = %d \t",Data9) ;printf("Status of Insertion Data = %d \n",Status) ;
    Status = Insert_End(&List ,Data10) ;printf("Data to inserte in the End List = %d \t",Data10) ;printf("Status of Insertion Data = %d \n",Status) ;
    printf("------------------------------------------------\n") ;
    Status = Display_Forward_Data(List) ;printf("Status of Display Data Forward = %d \n",Status) ;
    printf("------------------------------------------------\n") ;
    Status = Display_Back_Data(List) ;printf("Status of Display Data Back = %d \n",Status) ;
    printf("------------------------------------------------\n") ;
    Status = Display_Forward_Addressies(List) ;printf("Status of Display Data Forward = %d \n",Status) ;
    printf("------------------------------------------------\n") ;
    Status = Display_Back_Addressies(List) ;printf("Status of Display Data Back = %d \n",Status) ;
    printf("------------------------------------------------\n") ;
    Length = GetLength(List) ;printf("Number of the Element in the List = %d \n",Length) ;
    printf("------------------------------------------------\n") ;
    Status = Insert_After(List ,3 ,Data11) ;printf("Data to inserte in the End List = %d \t",Data11) ;printf("Status of Insertion Data = %d \n",Status) ;
    Status = Insert_After(List ,6 ,Data12) ;printf("Data to inserte in the End List = %d \t",Data12) ;printf("Status of Insertion Data = %d \n",Status) ;
    Status = Insert_After(List ,4 ,Data13) ;printf("Data to inserte in the End List = %d \t",Data13) ;printf("Status of Insertion Data = %d \n",Status) ;
    Status = Insert_After(List ,0 ,Data13) ;printf("Data to inserte in the End List = %d \t",Data13) ;printf("Status of Insertion Data = %d \n",Status) ;
    printf("------------------------------------------------\n") ;
    Status = Display_Forward_Data(List) ;printf("Status of Display Data Forward = %d \n",Status) ;
    printf("------------------------------------------------\n") ;
    Status = Display_Back_Data(List) ;printf("Status of Display Data Back = %d \n",Status) ;
    printf("------------------------------------------------\n") ;
    Status = Display_Forward_Addressies(List) ;printf("Status of Display Data Forward = %d \n",Status) ;
    printf("------------------------------------------------\n") ;
    Status = Display_Back_Addressies(List) ;printf("Status of Display Data Back = %d \n",Status) ;
    printf("------------------------------------------------\n") ;
    Length = GetLength(List) ;printf("Number of the Element in the List = %d \n",Length) ;
    printf("------------------------------------------------\n") ;
    Status = Delete_Beggining(&List)  ;printf("Status of Deletion Data = %d \n",Status) ;
    Status = Delete_Beggining(&List) ;printf("Status of Deletion Data = %d \n",Status) ;
    Status = Delete_Beggining(&List)  ;printf("Status of Deletion Data = %d \n",Status) ;
    Status = Delete_Beggining(&List)  ;printf("Status of Deletion Data = %d \n",Status) ;
    printf("------------------------------------------------\n") ;
    Status = Display_Forward_Data(List) ;printf("Status of Display Data Forward = %d \n",Status) ;
    printf("------------------------------------------------\n") ;
    Status = Display_Back_Data(List) ;printf("Status of Display Data Back = %d \n",Status) ;
    printf("------------------------------------------------\n") ;
    Status = Display_Forward_Addressies(List) ;printf("Status of Display Data Forward = %d \n",Status) ;
    printf("------------------------------------------------\n") ;
    Status = Display_Back_Addressies(List) ;printf("Status of Display Data Back = %d \n",Status) ;
    printf("------------------------------------------------\n") ;
    Length = GetLength(List) ;printf("Number of the Element in the List = %d \n",Length) ;
    printf("------------------------------------------------\n") ;
    Status = Delete_Index(List,1)  ;printf("Status of Deletion Data = %d \n",Status) ;
    Status = Delete_Index(List,0)  ;printf("Status of Deletion Data = %d \n",Status) ;
    Status = Delete_Index(List ,4) ;printf("Status of Deletion Data = %d \n",Status) ;
    Status = Delete_Index(List ,6)  ;printf("Status of Deletion Data = %d \n",Status) ;
    Status = Delete_Index(List ,3)  ;printf("Status of Deletion Data = %d \n",Status) ;
    Status = Delete_Index(List ,6)  ;printf("Status of Deletion Data = %d \n",Status) ;
    printf("------------------------------------------------\n") ;
    Status = Display_Forward_Data(List) ;printf("Status of Display Data Forward = %d \n",Status) ;
    printf("------------------------------------------------\n") ;
    Status = Display_Back_Data(List) ;printf("Status of Display Data Back = %d \n",Status) ;
    printf("------------------------------------------------\n") ;
    Status = Display_Forward_Addressies(List) ;printf("Status of Display Data Forward = %d \n",Status) ;
    printf("------------------------------------------------\n") ;
    Status = Display_Back_Addressies(List) ;printf("Status of Display Data Back = %d \n",Status) ;
    printf("------------------------------------------------\n") ;
    Length = GetLength(List) ;printf("Number of the Element in the List = %d \n",Length) ;
    printf("------------------------------------------------\n") ;
    printf("------------------------------------------------\n") ;
    Data = Retrieve_Data(List , 5,&Status);printf("Data Retrieved from the list = %d \t",Data) ;printf("Status of Retrieve Data = %d \n",Status) ;
    Data = Retrieve_Data(List , 1,&Status);printf("Data Retrieved from the list = %d \t",Data) ;printf("Status of Retrieve Data = %d \n",Status) ;
    Data = Retrieve_Data(List , 2,&Status);printf("Data Retrieved from the list = %d \t",Data) ;printf("Status of Retrieve Data = %d \n",Status) ;
    printf("------------------------------------------------\n") ;
    printf("------------------------------------------------\n") ;
    Status = Delete_Beggining(&List)  ;printf("Status of Deletion Data = %d \n",Status) ;
    Status = Delete_Beggining(&List) ;printf("Status of Deletion Data = %d \n",Status) ;
    Status = Delete_Beggining(&List)  ;printf("Status of Deletion Data = %d \n",Status) ;
    Status = Delete_Beggining(&List)  ;printf("Status of Deletion Data = %d \n",Status) ;
    Status = Delete_Beggining(&List)  ;printf("Status of Deletion Data = %d \n",Status) ;
    Status = Delete_Beggining(&List)  ;printf("Status of Deletion Data = %d \n",Status) ;
    Status = Delete_Beggining(&List)  ;printf("Status of Deletion Data = %d \n",Status) ;
    printf("------------------------------------------------\n") ;
    Status = Display_Forward_Data(List) ;printf("Status of Display Data Forward = %d \n",Status) ;
    printf("------------------------------------------------\n") ;
    Status = Display_Back_Data(List) ;printf("Status of Display Data Back = %d \n",Status) ;
    printf("------------------------------------------------\n") ;
    Status = Display_Forward_Addressies(List) ;printf("Status of Display Data Forward = %d \n",Status) ;
    printf("------------------------------------------------\n") ;
    Status = Display_Back_Addressies(List) ;printf("Status of Display Data Back = %d \n",Status) ;
    printf("------------------------------------------------\n") ;
    Length = GetLength(List) ;printf("Number of the Element in the List = %d \n",Length) ;
    printf("------------------------------------------------\n") ;
    Status = Insert_End(&List ,Data10) ;printf("Data to inserte in the End List = %d \t",Data10) ;printf("Status of Insertion Data = %d \n",Status) ;
    printf("------------------------------------------------\n") ;
    Status = Display_Forward_Data(List) ;printf("Status of Display Data Forward = %d \n",Status) ;
    printf("------------------------------------------------\n") ;
    Status = Display_Back_Data(List) ;printf("Status of Display Data Back = %d \n",Status) ;
    printf("------------------------------------------------\n") ;
    Status = Display_Forward_Addressies(List) ;printf("Status of Display Data Forward = %d \n",Status) ;
    printf("------------------------------------------------\n") ;
    Status = Display_Back_Addressies(List) ;printf("Status of Display Data Back = %d \n",Status) ;
    printf("------------------------------------------------\n") ;
    Length = GetLength(List) ;printf("Number of the Element in the List = %d \n",Length) ;
    printf("------------------------------------------------\n") ;
    Status = Insert_After(List ,1 ,Data13) ;printf("Data to inserte in the End List = %d \t",Data13) ;printf("Status of Insertion Data = %d \n",Status) ;
    printf("------------------------------------------------\n") ;
    Status = Display_Forward_Data(List) ;printf("Status of Display Data Forward = %d \n",Status) ;
    printf("------------------------------------------------\n") ;
    Status = Display_Back_Data(List) ;printf("Status of Display Data Back = %d \n",Status) ;
    printf("------------------------------------------------\n") ;
    Status = Display_Forward_Addressies(List) ;printf("Status of Display Data Forward = %d \n",Status) ;
    printf("------------------------------------------------\n") ;
    Status = Display_Back_Addressies(List) ;printf("Status of Display Data Back = %d \n",Status) ;
    printf("------------------------------------------------\n") ;
    Length = GetLength(List) ;printf("Number of the Element in the List = %d \n",Length) ;
    printf("------------------------------------------------\n") ;
    return 0;
}
